
[2021-11-14 00:00:07 -0800] [6697] [INFO] Starting gunicorn 20.1.0
[2021-11-14 00:00:07 -0800] [6697] [INFO] Listening at: http://127.0.0.1:8000 (6697)
[2021-11-14 00:00:07 -0800] [6697] [INFO] Using worker: sync
[2021-11-14 00:00:07 -0800] [6703] [INFO] Booting worker with pid: 6703
[2021-11-14 00:00:07 -0800] [6703] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_py'
[2021-11-14 00:00:07 -0800] [6703] [INFO] Worker exiting (pid: 6703)
[2021-11-14 00:00:08 -0800] [6697] [INFO] Shutting down: Master
[2021-11-14 00:00:08 -0800] [6697] [INFO] Reason: Worker failed to boot.
